import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name: 'John',
            email: 'admin@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: true,
        },
        {
            name: 'Janne',
            email: 'user@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: false,
        },
    ],
    products: [
        {
            name: 'Rope Original',
            slug: 'rope-original',
            category: 'Rope',
            image: 'https://res.cloudinary.com/dtqbattvc/image/upload/v1647322839/amazona/rope_td7ucd.jpg',
            price: 85,
            brand: 'B.Diamond',
            rating: 4.1,
            numReviews: 10,
            countInStock: 20,
            description:
                'LightWeight rope designed to help you send your hardest projects',
        },
        {
            name: 'Golden Quickdraws',
            slug: 'golden-quickdraws',
            category: 'Quickdraws',
            image: 'https://res.cloudinary.com/dtqbattvc/image/upload/v1647322838/amazona/quickdraws_rqv0bw.jpg',
            isFeatured: true,
            featuredImage:
                'https://res.cloudinary.com/dtqbattvc/image/upload/v1647322838/amazona/quickdraws_rqv0bw.jpg',
            price: 65,
            brand: 'B.Diamond',
            rating: 4.2,
            numReviews: 10,
            countInStock: 20,
            description: 'Pack of 6 Golden Quickdraws',
        },
        {
            name: 'Green Quickdraws',
            slug: 'green-quickdraws',
            category: 'Quickdraws',
            image: 'https://res.cloudinary.com/dtqbattvc/image/upload/v1647322838/amazona/quickdraws2_hyp2t2.jpg',
            price: 62,
            brand: 'Edelrid',
            rating: 4.1,
            numReviews: 10,
            countInStock: 20,
            description: 'Pack of 6 Green Quickdraws',
        },
        {
            name: 'Orange Rope',
            slug: 'orange-rope',
            category: 'Rope',
            image: 'https://res.cloudinary.com/dtqbattvc/image/upload/v1647322837/amazona/rope3_t4gdnt.jpg',
            isFeatured: true,
            featuredImage:
                'https://res.cloudinary.com/dtqbattvc/image/upload/v1647322837/amazona/rope3_t4gdnt.jpg',
            price: 85,
            brand: 'Beal',
            rating: 4.4,
            numReviews: 10,
            countInStock: 20,
            description: 'Smart looking rope, perfect for outdoor climbing',
        },
        {
            name: 'Blue Rope',
            slug: 'blue-rope',
            category: 'Rope',
            image: 'https://res.cloudinary.com/dtqbattvc/image/upload/v1647322837/amazona/rope2_f7gulq.jpg',
            price: 95,
            brand: 'Petzl',
            rating: 4.29,
            numReviews: 10,
            countInStock: 20,
            description: 'One of the best ropes on the market',
        },
        {
            name: 'Classic Shoes',
            slug: 'classic-shoes',
            category: 'Shoes',
            image: 'https://res.cloudinary.com/dtqbattvc/image/upload/v1647322835/amazona/climbing_shoes_wuvca0.jpg',
            price: 110,
            brand: 'FiveTen',
            rating: 4.25,
            numReviews: 10,
            countInStock: 20,
            description:
                'Polyvalent climbing shoes that will take you on top of every routes',
        },
        {
            name: 'Climbing Chock',
            slug: 'climbing-chock',
            category: 'Gears',
            image: 'https://res.cloudinary.com/dtqbattvc/image/upload/v1647322835/amazona/coinceur_s8vnhl.jpg',
            price: 50,
            brand: 'Petzl',
            rating: 4.03,
            numReviews: 10,
            countInStock: 20,
            description:
                'Sturdy and durable, it will follow you in all your trad climbs',
        },
        {
            name: 'Climbing Helmet',
            slug: 'climbing-helmet',
            category: 'Helmet',
            image: 'https://res.cloudinary.com/dtqbattvc/image/upload/v1647322836/amazona/helmet_tcrgek.jpg',
            price: 75,
            brand: 'Petzl',
            rating: 4.01,
            numReviews: 10,
            countInStock: 20,
            description:
                'No helmet feeling, perfect to send your projects with the safty wearing a helmet',
        },
        {
            name: 'Indoor Holds',
            slug: 'indoor-holds',
            category: 'Holds',
            image: 'https://res.cloudinary.com/dtqbattvc/image/upload/v1647322836/amazona/indoor_dh0rko.jpg',
            price: 60,
            brand: 'Beal',
            rating: 4.3,
            numReviews: 10,
            countInStock: 20,
            description: 'A set of 20 indoor holds',
        },
        {
            name: 'Belay 8 Device',
            slug: 'belay-device',
            category: 'Gears',
            image: 'https://res.cloudinary.com/dtqbattvc/image/upload/v1647333696/amazona/BelayDevice_ut1eyc.jpg',
            price: 87,
            brand: 'Beal',
            rating: 4.27,
            numReviews: 10,
            countInStock: 20,
            description: 'Classic but reliable belay device',
        },
        {
            name: 'Ultra Light Harness',
            slug: 'ultra-light-harness',
            category: 'Harness',
            image: 'https://res.cloudinary.com/dtqbattvc/image/upload/v1647333890/amazona/devers_yidd7m.jpg',
            isFeatured: true,
            featuredImage:
                'https://res.cloudinary.com/dtqbattvc/image/upload/v1647333890/amazona/devers_yidd7m.jpg',
            price: 105,
            brand: 'Petzl',
            rating: 4.33,
            numReviews: 10,
            countInStock: 20,
            description:
                'One of the lightest Harness, made for competition, but also perfect to send the hardest projects out there',
        },
        {
            name: 'Climbing Helmet BD',
            slug: 'climbing-helmet-bd',
            category: 'Helmet',
            image: 'https://res.cloudinary.com/dtqbattvc/image/upload/v1647334176/amazona/HelmetBD_vio1vv.jpg',
            price: 78,
            brand: 'B.Diamond',
            rating: 4.31,
            numReviews: 10,
            countInStock: 20,
            description:
                'Perfect to send your projects with the safty wearing a helmet without even feeling it',
        },
    ],
};
export default data;
