import Head from 'next/head';
import styles from './DefaultLayout.module.scss';
import Header from '../../modules/Header';
import Footer from '../../modules/Footer';
import { useContext, useEffect, useState } from 'react';
import { Store } from '../../../utils/Store';
import Cookies from 'js-cookie';

const DefaultLayout = ({
    title,
    children,
}: {
    title?: string;
    children: JSX.Element;
}) => {
    const { state } = useContext(Store);
    const { darkMode } = state;
    const [theme, setTheme] = useState('light-mode');

    useEffect(() => {
        const themeChecker = () => {
            if (Cookies.get('darkMode' || darkMode === true) === 'ON') {
                return 'dark-mode';
            } else return 'light-mode';
        };
        setTheme(themeChecker());
    }, [darkMode]);

    return (
        <div className={styles[`${theme}`]}>
            <Head>
                <title>
                    {title ? `${title} - Amazona Next` : 'Amazona Next'}
                </title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Header />

            <main className={styles.main}>{children}</main>

            <Footer />
        </div>
    );
};

export default DefaultLayout;
